# Generated by Django 5.2 on 2025-05-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeTag',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_class',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('PRATO_PRINCIPAL', 'Prato Principal'), ('SOBREMESA', 'Sobremesa'), ('LANCHE', 'Lanche'), ('ANIVERSARIO_VEGANO', 'Aniversário Vegano'), ('SUCO', 'Suco'), ('DRINK', 'Drink'), ('VEG_FRIOS', 'Veg Frios'), ('VEG_CARNES', 'Veg Carnes')], max_length=50),
        ),
    ]
