# Generated by Django 5.2 on 2025-06-06 17:44

import core.validators
import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_populate_recipe_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe_images/', validators=[core.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to=recipes.models.recipe_image_path, validators=[core.validators.validate_image]),
        ),
    ]
