# Generated by Django 5.2 on 2025-06-10 15:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_image_alter_recipeimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeimage',
            options={'ordering': ['-is_primary', '-created_at']},
        ),
        migrations.RenameField(
            model_name='recipeimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
