# Generated by Django 5.2 on 2025-06-10 15:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_image_alter_recipeimage_image'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Renomear uploaded_at para created_at se a coluna uploaded_at existir
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'recipes_recipeimage' AND column_name = 'uploaded_at') THEN
                    ALTER TABLE recipes_recipeimage RENAME COLUMN uploaded_at TO created_at;
                END IF;
                
                -- Adicionar updated_at se não existir
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'recipes_recipeimage' AND column_name = 'updated_at') THEN
                    ALTER TABLE recipes_recipeimage ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
                END IF;
            END
            $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'recipes_recipeimage' AND column_name = 'created_at') THEN
                    ALTER TABLE recipes_recipeimage RENAME COLUMN created_at TO uploaded_at;
                END IF;
                ALTER TABLE recipes_recipeimage DROP COLUMN IF EXISTS updated_at;
            END
            $$;
            """
        ),
    ]
